configure: check for gmodule
on ubuntu:

/bin/ld: src/fe-gtk/sexy-spell-entry.o: undefined reference to symbol 'g_module_open'
/bin/ld: /lib/x86_64-linux-gnu/libgmodule-2.0.so.0: error adding symbols: DSO missing from command line